<a href="https://colab.research.google.com/github/programmermahi/AL_Assignment/blob/main/fpgrowth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas  as pd

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/Ataullha/CSE-436-Data-Mining-Lab/refs/heads/main/transaction_data.csv")

In [3]:
df

  Transaction Item1 Item2 Item3 Item4 Item5
0          T1     A     B     C     D     E
1          T2     A     C     D     E     F
2          T3     A     B     E   NaN   NaN
3          T4     A     C     F     G     H
4          T5     B     C     D     E     F

In [4]:
df=df.fillna('*')

In [5]:
df

  Transaction Item1 Item2 Item3 Item4 Item5
0          T1     A     B     C     D     E
1          T2     A     C     D     E     F
2          T3     A     B     E     *     *
3          T4     A     C     F     G     H
4          T5     B     C     D     E     F

In [6]:
df=df.drop('Transaction',axis=1)

In [7]:
df

  Item1 Item2 Item3 Item4 Item5
0     A     B     C     D     E
1     A     C     D     E     F
2     A     B     E     *     *
3     A     C     F     G     H
4     B     C     D     E     F

In [8]:
from mlxtend.preprocessing import TransactionEncoder

In [9]:
te= TransactionEncoder()

In [10]:
te_ary=te.fit_transform(df.values.tolist())

In [11]:
te_ary=te_ary.tolist()

In [12]:
df

  Item1 Item2 Item3 Item4 Item5
0     A     B     C     D     E
1     A     C     D     E     F
2     A     B     E     *     *
3     A     C     F     G     H
4     B     C     D     E     F

In [13]:
df.values.tolist()

[['A', 'B', 'C', 'D', 'E'],
 ['A', 'C', 'D', 'E', 'F'],
 ['A', 'B', 'E', '*', '*'],
 ['A', 'C', 'F', 'G', 'H'],
 ['B', 'C', 'D', 'E', 'F']]

In [15]:
te_ary

[[False, True, True, True, True, True, False, False, False],
 [False, True, False, True, True, True, True, False, False],
 [True, True, True, False, False, True, False, False, False],
 [False, True, False, True, False, False, True, True, True],
 [False, False, True, True, True, True, True, False, False]]

In [16]:
te.columns_

['*', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [17]:
transc_df=pd.DataFrame(te_ary,columns=te.columns_)

In [18]:
transc_df

       *      A      B      C      D      E      F      G      H
0  False   True   True   True   True   True  False  False  False
1  False   True  False   True   True   True   True  False  False
2   True   True   True  False  False   True  False  False  False
3  False   True  False   True  False  False   True   True   True
4  False  False   True   True   True   True   True  False  False

In [19]:
transc_df=transc_df.drop('*',axis=1)

In [20]:
transc_df

       A      B      C      D      E      F      G      H
0   True   True   True   True   True  False  False  False
1   True  False   True   True   True   True  False  False
2   True   True  False  False   True  False  False  False
3   True  False   True  False  False   True   True   True
4  False   True   True   True   True   True  False  False

In [22]:
#from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import fpgrowth

In [ ]:
 #rules=apriori(transc_df,min_support=.6,use_colnames=True)

In [23]:
rules=fpgrowth(transc_df,min_support=.6,use_colnames=True)

In [24]:
rules

    support   itemsets
0       0.8        (E)
1       0.8        (C)
2       0.8        (A)
3       0.6        (D)
4       0.6        (B)
5       0.6        (F)
6       0.6     (E, C)
7       0.6     (A, C)
8       0.6     (E, A)
9       0.6     (D, C)
10      0.6     (E, D)
11      0.6  (E, D, C)
12      0.6     (B, E)
13      0.6     (F, C)

In [25]:
from mlxtend.frequent_patterns import association_rules

In [27]:
assoc_rules=association_rules(rules,min_threshold=0.8)

In [28]:
assoc_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(D),(C),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
1,(D),(E),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
2,"(E, D)",(C),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
3,"(E, C)",(D),0.6,0.6,0.6,1.0,1.666667,1.0,0.24,inf,1.0,1.00,1.0,1.000
4,"(C, D)",(E),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
5,(D),"(E, C)",0.6,0.6,0.6,1.0,1.666667,1.0,0.24,inf,1.0,1.00,1.0,1.000
6,(B),(E),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875
7,(F),(C),0.6,0.8,0.6,1.0,1.250000,1.0,0.12,inf,0.5,0.75,1.0,0.875

In [ ]:
#Leaf nodes represent final decisions or predictions